import os

OPENAI_MODEL = os.getenv("OPENAI_MODEL", "gpt-4.1-mini")

MAX_RECORDS_PER_QUERY = 20
MAX_SESSION_RECORDS = 100

RISK_THRESHOLD_TERMINATE = 0.8
RISK_THRESHOLD_RESTRICT = 0.6
RISK_THRESHOLD_AUTH = 0.4
